[package]
name = "mursl"
version = "0.1.0"
authors = ["Adam Perry <adam.n.perry@gmail.com>"]

[lib]
name = "mursl"
crate-type = ["staticlib", "dylib"]

[dependencies]
rlibc = "1.0.0"
syscall = "0.2.1"
